### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [great-houk/mouse-project#2]
Hello!

I found this project from https://hackaday.com/2022/08/15/diy-gaming-mouse-beats-the-competition-costs-less/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and PCB files in any purpose?
It would be great to see any popular open source license.

**Comment by great-houk** [comment]
Hi! Sorry about that, I'm still somewhat new to github and forgot to add one. Thanks for letting me know!

**Comment by vazhnov** [comment]
MIT license — amazing!
Thank you very much!
